### PR TITLE
Page Bean

### PR DESCRIPTION
**Pull request by AlexanderVladimirov9090**
Done with Page Bean Task.

### CODE REVIEW

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by mgenov** [comment]
I'll go into it till the end of the day.


On Wednesday, June 8, 2016, Alexander Vladimirov <notifications@github.com>
wrote:

> Done.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/clouway-incubator/collections/pull/5#issuecomment-224568770>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMxRzNSwKtArQaBlz-E3qDGK_WHVmVeks5qJq9egaJpZM4Iwple>
> .
>


-- 
Regards,
  Miroslav Genov

**Comment by AlexanderVladimirov9090** [comment]
OK, Tomorrow will make pull req for Sentence Task.

**Comment by mgenov** [comment]
LGTM !

**Comment by AlexanderVladimirov9090** [comment]
Tomorow will sqash and push.

**Pull request merged**
